language: java
sudo: false
os:
- linux
notifications:
  email: false
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.m2/wrapper"
env:
  global:
  - _JAVA_OPTIONS=
install:
- true
script:
- "./test"
before_cache:
- rm -fr $HOME/.m2/repository/kr/motd/maven/os-maven-plugin
